language: python
python:
    - "3.8"
env:
  - NUMBA_DISABLE_JIT=1

before_install:
    - pip install coveralls
    - pip install pytest==3.10.1
    - pip install pytest-ordering==0.5

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - coverage run --source DataProcessingTools -m py.test -s -q

after_success:
    - coverage report
    - coveralls
